<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAddress</name>
   <tag></tag>
   <elementGuidId>71bf9a59-fce1-468b-bbf7-6a778335aaf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblAddress</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
