<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCity</name>
   <tag></tag>
   <elementGuidId>64054b6e-a200-48c5-9483-a3bf56598a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblCity</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
