<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPCode</name>
   <tag></tag>
   <elementGuidId>ec0d0432-4a32-45cf-8d6e-7288b1355d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblPCode</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
