<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPhoneNumber</name>
   <tag></tag>
   <elementGuidId>5217faba-1b47-4ef1-9a63-b2c4b538576c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblPhoneNumber</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
