<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>progressBar3</name>
   <tag></tag>
   <elementGuidId>417d4c51-0ae7-42ea-bf6d-e7ef6be627ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#progBar3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
