<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_R5C3_Incomplete</name>
   <tag></tag>
   <elementGuidId>73610ef0-9893-46f9-9943-14986cbd3016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;route-table&quot;)/tbody[1]/tr[5]/td[@aria-colindex=&quot;3&quot;]/span[count(. | //*[@class = 'incomplete']) = count(//*[@class = 'incomplete'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route-table&quot;)/tbody[1]/tr[5]/td[@aria-colindex=&quot;3&quot;]/span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>incomplete</value>
   </webElementProperties>
</WebElementEntity>
