<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_R1_Date</name>
   <tag></tag>
   <elementGuidId>4434c4b1-f42a-4bac-a8a8-787a23e0f410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;route-table&quot;)/tbody[1]/tr[1]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
